<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Usulan_tambahan_model extends Model
{

    public $table = 'user_tst';
    public $id = 'id';
    public $order = 'DESC';

    function Usulan_tambahan_model()
    {
        parent::Model();
    }

    // datatables
    function json() {
        $this->datatables->select('id,user_name,email');
        $this->datatables->from('user_tst');
        //add this line for join
        //$this->datatables->join('table2', 'usulan_tambahan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('usulan_tambahan/read/$1'),'Read')." | ".anchor(site_url('usulan_tambahan/update/$1'),'Update')." | ".anchor(site_url('usulan_tambahan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('cif', $q);
	$this->db->or_like('jenis_cif', $q);
	$this->db->or_like('nama_nasabah', $q);
	$this->db->or_like('cif_utama', $q);
	$this->db->or_like('hubungan_degan_utama', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('approval', $q);
	$this->db->or_like('tanggal_kirim', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('cif', $q);
	$this->db->or_like('jenis_cif', $q);
	$this->db->or_like('nama_nasabah', $q);
	$this->db->or_like('cif_utama', $q);
	$this->db->or_like('hubungan_degan_utama', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('approval', $q);
	$this->db->or_like('tanggal_kirim', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Usulan_tambahan_model.php */
/* Location: ./application/models/Usulan_tambahan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-09 09:01:26 */
/* http://harviacode.com */